apiVersion: apps/v1
kind: Deployment
metadata:
  name: petkeep-server
  labels:
    app: petkeep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petkeep
  template:
    metadata:
      labels:
        app: petkeep
    spec:
      containers:
      - name: petkeep-server
        image: rizkybiz/petkeep-server:latest
        ports:
        - containerPort: 8080
        env:
          - name: API_PORT
            value: "8080"
          - name: API_DATABASE_HOST
            value: "cockroachdb"
          - name: API_DATABASE_PORT
            value: "26257"
          - name: API_DATABASE_USER
            value: "petkeep"
          - name: API_DATABASE_NAME
            value: "petkeep"
          - name: API_JWT_SIGNING_KEY
            value: "rand0m"
          - name: API_LOG_LEVEL
            value: "DEBUG"
          - name: API_INSECURE_DATABASE_CONNECTION
            value: "true"
          - name: API_STATSD_HOST
            value: "broker"
          - name: API_STATSD_PORT
            value: "8125"